### ISSUE TITLE
Fails when using console.error() or when passing multiple parameters

### ISSUE THREAD

**Issue by SeanBannister** [icodeforlove/Console.js#6]
I noticed if you pass multiple parameters like `console.log('first', 'second')` or if you use `console.error('test')` console.js fails.

**Comment by icodeforlove** [comment]
This will be fixed in the next rebuild (#13).

It needs to support `console.log('first'.red, {}, {})`, but the requirement being that the styled string is ALWAYS the first argument. The advantage is you can still style the first argument and then get native object logging on all the proceeding items.
